on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.23.x]
        goos: ["linux"]
        goarch: ["386"]
    env:
      CGO_ENABLED: 1
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: ${{ matrix.go-version }}

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date --iso-8601=seconds) >> ${GITHUB_ENV}

      - name: Install gcc multilib
        run: |
            sudo dpkg --add-architecture i386
            sudo apt-get -y update
            sudo apt-get install -y gcc-multilib

      - name: Build
        run: |
          go build -o dumbots.so -buildmode=c-shared -ldflags "-X 'github.com/et-nik/dumbots/main.Version=${{ env.APP_VERSION }}' -X 'github.com/et-nik/dumbots/main.BuildDate=${{ env.BUILD_TIME }}'"

      - name: Create publish directory
        run: |
          mkdir -p publish/addons/dumbots
          mv ./dumbots.so publish/addons/dumbots/
          cp README.md publish/

      - name: Arhive artifacts
        run: |
          cd publish
          tar -czvf ../dumbots_linux.tar.gz ./

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dumbots_linux.tar.gz
          asset_name: dumbots_linux.tar.gz
          tag: ${{ github.ref }}
          overwrite: true